stages:
  generate_data:
    cmd: python src/generate_data.py
    deps:
      - src/generate_data.py
    outs:
      - /code/data/data.csv
  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - /code/data/data.csv
    outs:
      - model.joblib
  train_model_v2:
    cmd: python src/train_model_v2.py
    deps:
      - src/train_model_v2.py
      - /code/data/data.csv
    outs:
      - model_v2.joblib
    
  train_model_v3:
    cmd: python src/train_model_v3.py
    deps:
      - src/train_model_v3.py
      - /code/data/data.csv
    outs:
      - model_v3.joblib

  train_model_v4:
    cmd: python src/train_model_v4.py
    deps:
      - src/train_model_v4.py
      - /code/data/data.csv
    outs:
      - model_v4.joblib
