stages:
  generate_data:
    cmd: python src/generate_data.py
    deps:
      - src/generate_data.py
    outs:
      - data/data.csv
  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/data.csv
    outs:
      - model.joblib
  train_model_v2:
    cmd: python src/train_model_v2.py
    deps:
      - src/train_model_v2.py
      - data/data.csv
    outs:
      - model_v2.joblib
    
  train_model_v3:
    cmd: python src/train_model_v3.py
    deps:
      - src/train_model_v3.py
      - data/data.csv
    outs:
      - model_v3.joblib

  train_model_v4:
    cmd: python src/train_model_v4.py
    deps:
      - src/train_model_v4.py
      - data/data.csv
    outs:
      - model_v4.joblib
    

  train_model_v5:
    cmd: python src/train_model_v5.py
    deps:
      - src/train_model_v5.py
      - data/data.csv
    outs:
      - models/wip_1_model.joblib

artifacts:
  model:
    path: models/wip_1_model.joblib
    type: model
    desc: "Random Forest model version 1"