stages:
  generate_data:
    cmd: python src/generate_data.py
    deps:
      - src/generate_data.py
    outs:
      - /code/data/data.csv
  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - /code/data/data.csv
    outs:
      - model.joblib
  # train_model_v2:
  #   cmd: python train_model_v2.py
  #   deps:
  #     - train_model_v2.py
  #     - /data/data.csv
  #   outs:
  #     - model_v2.joblib
